# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RT_sampler_cpp <- function(Y, M, burnin, seed, prior) {
    .Call(`_RTsampler_RT_sampler_cpp`, Y, M, burnin, seed, prior)
}

